[project]
name = "recon"
version = "0.1.0"
description = "Reconnaissance toolkit"
readme = "README.md"
authors = [
    { name = "bbbmasterlolz", email = "82566017+bbbmasterlolz@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "requests>=2.31.0",
    "playwright",
    "tree-sitter>=0.26.0",
    "tree-sitter-javascript>=0.25.0",
    "reportlab>=5.0.1",
]

[project.scripts]
recon = "recon.cli:main"
reconAPI = "recon.cli:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

